baseURL = "https://manoedinata.me"
languageCode = "id-ID"
title = "Hendra Manudinata"
theme = "PaperMod"
disqusShortname = "manoedinata"

[params]
comments = "true"
ShowToc = "true"

[params.homeInfoParams]
title = "Sugeng Rawuh... Kula Hendra ğŸ™"
content = "Selamat datang di website saya!"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/manoedinata"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/manoedinata"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/manoedinata"

[[params.socialIcons]]
name = "Email"
url = "mailto:manoedinata@gmail.com"
