baseURL = "https://www.manoe.my.id/"
languageCode = "id-ID"
title = "Hendra Manudinata"
theme = "PaperMod"

[params.homeInfoParams]
title = "Sugeng Rawuh... Kula Hendra ğŸ™"
content = "Selamat datang di website saya!"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/manoedinata"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/manoedinata"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/manoedinata"

[[params.socialIcons]]
name = "Email"
url = "mailto:manoedinata@gmail.com"
